version: "3.9"

services:
  postgres:
    image: postgres:15
    container_name: auth_postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: auth_user
      POSTGRES_PASSWORD: auth_pass
      POSTGRES_DB: auth_db
    volumes:
      - auth_pgdata:/var/lib/postgresql/data

volumes:
  auth_pgdata:
